; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_echo = yes
build_unflags = 
	-std=gnu++11
	-fno-rtti
build_flags = 
    -std=gnu++17
build_type = release ;debug; release; debug_with_optimization

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
lib_deps = 
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    marvinroger/AsyncMqttClient@^0.9.0
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/DHT sensor library@^1.4.6

build_flags = 
    -DARDUINO_COREDUMP_ENABLE=1 ; Core-Dump aktivieren
    -DARDUINO_COREDUMP_ENABLE_TO_FLASH=1 ; Core-Dump in Flash speichern
 

    ; Core-Features deaktivieren für Speicherersparnis
    ;-DCONFIG_BT_ENABLED=0                    ; Bluetooth komplett aus -> so hat's keine wirkung, da nicht die erste definition beim compilieren
    -DCONFIG_WIFI_ENABLED=1                  ; WiFi explizit aktivieren
    ;-DCONFIG_ESP_CONSOLE_UART_DEFAULT=0      ; Console UART aus
    ;-DCONFIG_LOG_DEFAULT_LEVEL=0             ; Logging minimal
    ;-DCONFIG_ESP_ERR_TO_NAME_LOOKUP=0        ; Error-Namen-Lookup aus
    ;-DCONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=2048  ; Event Task Stack reduzieren
    
    ; Arduino-spezifische Optimierungen für Speicherersparnis
    ;-DCORE_DEBUG_LEVEL=0                     ; Arduino Debug aus
    ;-DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=0     ; HAL Logging aus

;build_unflags =
;    -DCONFIG_BT_ENABLED=1 ; Bluetooth komplett aus - hat nix gebracht ...
;build_src_filter =
;    +<*>
;    -<+<../arduino/cores/esp32/bt/*>>  ; Bluetooth Core ausschließen